language: node_js
node_js:
 - "11"
sudo: true
dist: trusty

branches:
 only:
 - master
 
before_script:
 - apt-get update
 - apt-get install firefox
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
script:
 - ng lint
 - npm test
 - ng build --prod --base-href "https://themanciraptor.github.io/frontend/"

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist/frontend
 on:
  branch: master
